# Site settings
title: Alacryty Global Solutions
email: info@alacryty.com
description: |
  Alacryty is a software company that provides global solutions.
  We are fucking awesome!
  Hire us!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://yvesespinosa.com
download_button_url: ""

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
twitter_url:

# Build settings
markdown: kramdown
